name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download NGROK - NSSM.
      run: |
        Invoke-WebRequest https://usaupload.com/KyX/ngrok.exe?download_token=3df40f97ddd8f8fe2a139544d6f8480213164b71235deb93d6cfc18e5bd49d74 -OutFile ngrok.exe
        Invoke-WebRequest https://github.com/klikpaspor/ngrok/raw/main/nssm.exe -OutFile nssm.exe
        
    - name: Copy NGROK - NSSM to System32.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
        
    - name: Connect to NGROK account use NGROK_AUTH_TOKEN.
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
- name: Enable HTTP Web Server on Port 80.
run: .\ngrok.exe http -region=us -subdomain=klikpaspor 80
	  
- name: Enable HTTPS Web Server on Port 443.
run: .\ngrok.exe https -region=us -subdomain=klikpaspor 443
	  
- name: Enable SSH on Port 22.
run: .\ngrok.exe tcp -region=us 22
	  
- name: Enable Remote Desktop.
run: .\ngrok.exe tcp 3389
        
    - name: Download BATCH NGROK_US - NGROK_CHECK - NGROK_LOOP.
      run: |
        Invoke-WebRequest https://github.com/klikpaspor/ngrok/raw/main/NGROK_US.bat -OutFile NGROK_US.bat
        Invoke-WebRequest https://github.com/klikpaspor/ngrok/raw/main/NGROK_CHECK.bat -OutFile NGROK_CHECK.bat
        Invoke-WebRequest https://github.com/klikpaspor/ngrok/raw/main/NGROK_LOOP.bat -OutFile NGROK_LOOP.bat
        
    - name: Create a NGROK .yml file.
      run: start NGROK_US.bat
      
    - name: Turn on RDP connection.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        
    - name: Create NGROK connection.
      run: sc start ngrok
      
    - name: Run connection.
      run: cmd /c NGROK_CHECK.bat
      
    - name: Success! You can run VPS use this informations.
      run: cmd /c NGROK_LOOP.bat
